# Generated by Django 4.2.1 on 2024-12-03 03:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('administrativo', 'administrativo'), ('Psicologo', 'Psicologo'), ('Fonoaudiologo', 'Fonoaudiologo'), ('psiquiatra', 'psiquiatra'), ('psicopedagogo', 'psicopedagogo'), ('otro', 'otro')], default='Psicologo', max_length=25)),
                ('comentario', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True)),
                ('identificador', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('dni', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('responables', models.CharField(blank=True, max_length=200)),
                ('motivo_consulta', models.CharField(blank=True, max_length=200)),
                ('derivado', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('alta', 'alta'), ('derivado', 'derivado')], default='activo', max_length=20)),
                ('profesional_responsable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.CharField(choices=[('8:00-8:45', '8:00-8:45'), ('8:45-9:30', '8:45-9:30'), ('9:30-10:15', '9:30-10:15'), ('10:15-11:00', '10:15-11:00'), ('11:00-11:45', '11:00-11:45'), ('11:45-12:30', '11:45-12:30'), ('12:30-13:15', '12:30-13:15'), ('13:15-14:00', '13:15-14:00'), ('14:00-14:45', '14:00-14:45'), ('14:45-15:30', '14:45-15:30'), ('15:30-16:15', '15:30-16:15'), ('16:15-17:00', '16:15-17:00'), ('17:00-17:15', '17:00-17:15'), ('17:15-18:30', '17:15-18:30'), ('18:30-19:15', '18:30-19:15'), ('19:15-20:00', '19:15-20:00'), ('20:00-20:45', '20:00-20:45'), ('20:45-21:30', '20:45-21:30')], default='1', max_length=20)),
                ('disponible', models.BooleanField(blank=True, default=False)),
                ('asistio', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
                ('profesional_responsable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('consulta', 'consulta'), ('informe', 'informe'), ('psicotecnico', 'psicotecnico'), ('peritaje', 'peritaje'), ('apto', 'apto')], default='consulta', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('saldado', 'saldado')], default='pendiente', max_length=20)),
                ('factura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.factura')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
                ('profesional_responsable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historiaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True)),
                ('detalle', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
                ('profesional_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente'),
        ),
        migrations.CreateModel(
            name='evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
                ('profesional_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('detalle', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
                ('profesional_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
