# Generated by Django 4.2.1 on 2025-01-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
