# Generated by Django 4.2.1 on 2023-06-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_derivacion_profesional_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True)),
                ('numero', models.IntegerField(blank=True)),
                ('paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.paciente')),
            ],
        ),
    ]
