# Generated by Django 4.2.1 on 2023-06-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_pago_comprobante_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.factura'),
            preserve_default=False,
        ),
    ]
