# Generated by Django 4.2.1 on 2024-01-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_turno_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('8:00-8:45', '1'), ('8:45-9:30', '2'), ('9:30-10:15', '3'), ('10:15-11:00', '4'), ('11:00-11:45', '5'), ('11:45-12:30', '6'), ('12:30-13:15', '7'), ('13:15-14:00', '8'), ('14:00-14:45', '9'), ('14:45-15:30', '10'), ('15:30-16:15', '11'), ('16:15-17:00', '12'), ('17:00-17:15', '13'), ('17:15-18:30', '14'), ('18:30-19:15', '15'), ('19:15-20:00', '16'), ('20:00-20:45', '17'), ('20:45-21:30', '18')], default='1', max_length=20),
        ),
    ]
