# Generated by Django 4.2.1 on 2024-01-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_turno_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('1', '8:00-8:45'), ('2', '8:45-9:30'), ('3', '9:30-10:15'), ('4', '10:15-11:00'), ('5', '11:00-11:45'), ('6', '11:45-12:30'), ('7', '12:30-13:15'), ('8', '13:15-14:00'), ('9', '14:00-14:45'), ('10', '14:45-15:30'), ('11', '15:30-16:15'), ('12', '16:15-17:00'), ('13', '17:00-17:15'), ('14', '17:15-18:30'), ('15', '18:30-19:15'), ('16', '19:15-20:00'), ('17', '20:00-20:45'), ('18', '20:45-21:30')], default='1', max_length=20),
        ),
    ]
